/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WildlifeTRouteImport } from './routes/wildlife-t'
import { Route as WildlifeRouteImport } from './routes/wildlife'
import { Route as VolunteerTRouteImport } from './routes/volunteer-t'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectTRouteImport } from './routes/project-t'
import { Route as NewsTRouteImport } from './routes/news-t'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForestsRouteImport } from './routes/forests'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminDriveRouteImport } from './routes/admin/drive'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCmsRouteImport } from './routes/admin/cms'

const WildlifeTRoute = WildlifeTRouteImport.update({
  id: '/wildlife-t',
  path: '/wildlife-t',
  getParentRoute: () => rootRouteImport,
} as any)
const WildlifeRoute = WildlifeRouteImport.update({
  id: '/wildlife',
  path: '/wildlife',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerTRoute = VolunteerTRouteImport.update({
  id: '/volunteer-t',
  path: '/volunteer-t',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectTRoute = ProjectTRouteImport.update({
  id: '/project-t',
  path: '/project-t',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsTRoute = NewsTRouteImport.update({
  id: '/news-t',
  path: '/news-t',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForestsRoute = ForestsRouteImport.update({
  id: '/forests',
  path: '/forests',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriveRoute = AdminDriveRouteImport.update({
  id: '/admin/drive',
  path: '/admin/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/admin/cms',
  path: '/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/forests': typeof ForestsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/news-t': typeof NewsTRoute
  '/project-t': typeof ProjectTRoute
  '/projects': typeof ProjectsRoute
  '/volunteer': typeof VolunteerRoute
  '/volunteer-t': typeof VolunteerTRoute
  '/wildlife': typeof WildlifeRoute
  '/wildlife-t': typeof WildlifeTRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drive': typeof AdminDriveRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/forests': typeof ForestsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/news-t': typeof NewsTRoute
  '/project-t': typeof ProjectTRoute
  '/projects': typeof ProjectsRoute
  '/volunteer': typeof VolunteerRoute
  '/volunteer-t': typeof VolunteerTRoute
  '/wildlife': typeof WildlifeRoute
  '/wildlife-t': typeof WildlifeTRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drive': typeof AdminDriveRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/forests': typeof ForestsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/news-t': typeof NewsTRoute
  '/project-t': typeof ProjectTRoute
  '/projects': typeof ProjectsRoute
  '/volunteer': typeof VolunteerRoute
  '/volunteer-t': typeof VolunteerTRoute
  '/wildlife': typeof WildlifeRoute
  '/wildlife-t': typeof WildlifeTRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drive': typeof AdminDriveRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/forests'
    | '/gallery'
    | '/login'
    | '/news'
    | '/news-t'
    | '/project-t'
    | '/projects'
    | '/volunteer'
    | '/volunteer-t'
    | '/wildlife'
    | '/wildlife-t'
    | '/admin/cms'
    | '/admin/dashboard'
    | '/admin/drive'
    | '/admin/members'
    | '/admin/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/forests'
    | '/gallery'
    | '/login'
    | '/news'
    | '/news-t'
    | '/project-t'
    | '/projects'
    | '/volunteer'
    | '/volunteer-t'
    | '/wildlife'
    | '/wildlife-t'
    | '/admin/cms'
    | '/admin/dashboard'
    | '/admin/drive'
    | '/admin/members'
    | '/admin/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/forests'
    | '/gallery'
    | '/login'
    | '/news'
    | '/news-t'
    | '/project-t'
    | '/projects'
    | '/volunteer'
    | '/volunteer-t'
    | '/wildlife'
    | '/wildlife-t'
    | '/admin/cms'
    | '/admin/dashboard'
    | '/admin/drive'
    | '/admin/members'
    | '/admin/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  ForestsRoute: typeof ForestsRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  NewsTRoute: typeof NewsTRoute
  ProjectTRoute: typeof ProjectTRoute
  ProjectsRoute: typeof ProjectsRoute
  VolunteerRoute: typeof VolunteerRoute
  VolunteerTRoute: typeof VolunteerTRoute
  WildlifeRoute: typeof WildlifeRoute
  WildlifeTRoute: typeof WildlifeTRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDriveRoute: typeof AdminDriveRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminProfileRoute: typeof AdminProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wildlife-t': {
      id: '/wildlife-t'
      path: '/wildlife-t'
      fullPath: '/wildlife-t'
      preLoaderRoute: typeof WildlifeTRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wildlife': {
      id: '/wildlife'
      path: '/wildlife'
      fullPath: '/wildlife'
      preLoaderRoute: typeof WildlifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer-t': {
      id: '/volunteer-t'
      path: '/volunteer-t'
      fullPath: '/volunteer-t'
      preLoaderRoute: typeof VolunteerTRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-t': {
      id: '/project-t'
      path: '/project-t'
      fullPath: '/project-t'
      preLoaderRoute: typeof ProjectTRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-t': {
      id: '/news-t'
      path: '/news-t'
      fullPath: '/news-t'
      preLoaderRoute: typeof NewsTRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forests': {
      id: '/forests'
      path: '/forests'
      fullPath: '/forests'
      preLoaderRoute: typeof ForestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drive': {
      id: '/admin/drive'
      path: '/admin/drive'
      fullPath: '/admin/drive'
      preLoaderRoute: typeof AdminDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/admin/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  ForestsRoute: ForestsRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  NewsTRoute: NewsTRoute,
  ProjectTRoute: ProjectTRoute,
  ProjectsRoute: ProjectsRoute,
  VolunteerRoute: VolunteerRoute,
  VolunteerTRoute: VolunteerTRoute,
  WildlifeRoute: WildlifeRoute,
  WildlifeTRoute: WildlifeTRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDriveRoute: AdminDriveRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminProfileRoute: AdminProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
